plugin: community.general.yc_compute

folders:
  - b1gv4l14uqqeafgtpcpr

auth_kind: serviceaccountfile

service_account_file: ./key.json

hostnames:
#  - fqdn
  - "{{name}}"

compose:
  ansible_host: network_interfaces[0].primary_v4_address.one_to_one_nat.address


keyed_groups:
 - key: labels['tags']
   prefix: ''
   separator: ''
