- name: Install ruby and build
  hosts: db
  become: true
  tasks:
    - name: Install transport https
      apt:
        name: apt-transport-https
        state: present
    - name: Install 'ca-certificates'
      apt:
        name: ca-certificates
        state: present
    - name: Install ruby-full
      apt:
        name: ruby-full
        state: present

    - name: Install ruby-bundler
      apt:
        name: ruby-bundler
        state: present

    - name: Install build-essential
      apt:
        name: build-essential
        state: present
