- name: Install MongoDB from repository yandex cloud
  hosts: all
  become: true
  tasks:
  - name: Install mongodb package
    apt:
      name: mongodb
      state: present

  - name: Configure service supervisor
    systemd:
      name: mongodb
      enabled: yes
